site_name: "Brief Connect Documentation"
site_url: "https://jeremystokese2.github.io/bcdocs"
theme:
  name: "material"

plugins:
  - search
  - awesome-pages

docs_dir: "./docs"
use_directory_urls: true

exclude_docs: |
  !.attachments*